CREATE DATABASE akshaytest;
USE akshaytest;

CREATE TABLE user (
  id int(11) NOT NULL AUTO_INCREMENT,
  NAME varchar(45) DEFAULT NULL,
  CITY varchar(45) DEFAULT NULL,
  AGE int(11) DEFAULT NULL,
  COUNTRY varchar(45) DEFAULT NULL,
  LANGUAGE varchar(45) DEFAULT NULL,
  CONTACT varchar(45) DEFAULT NULL,
  DESCRIPTION varchar(45) DEFAULT NULL,
  PRIMARY KEY (id)
);

/*
-- Query: SELECT * FROM akshaytest.user
LIMIT 0, 1000

-- Date: 2013-10-17 01:09
*/
INSERT INTO user (id,NAME,CITY,AGE,COUNTRY,LANGUAGE,CONTACT,DESCRIPTION) VALUES (1,'ABC','Mysore',11,'India','English','1234567891','Nothiing');
INSERT INTO user (id,NAME,CITY,AGE,COUNTRY,LANGUAGE,CONTACT,DESCRIPTION) VALUES (2,'ASD','Delhi',22,'India','English','1234567891','Nothiing');
INSERT INTO user (id,NAME,CITY,AGE,COUNTRY,LANGUAGE,CONTACT,DESCRIPTION) VALUES (3,'FGH','Chennai',23,'India','Hindi','99666666666','Nothiing');
INSERT INTO user (id,NAME,CITY,AGE,COUNTRY,LANGUAGE,CONTACT,DESCRIPTION) VALUES (4,'JKL','Bangalore',32,'India','Hindi','1234567891','Nothiing');
INSERT INTO user (id,NAME,CITY,AGE,COUNTRY,LANGUAGE,CONTACT,DESCRIPTION) VALUES (6,'QWE','Delhi',55,'India','English','99666666666','Nothiing');
INSERT INTO user (id,NAME,CITY,AGE,COUNTRY,LANGUAGE,CONTACT,DESCRIPTION) VALUES (7,'RTY','Bangalore',34,'India','Hindi','1234567891','Nothiing');
INSERT INTO user (id,NAME,CITY,AGE,COUNTRY,LANGUAGE,CONTACT,DESCRIPTION) VALUES (9,'Akshay','Mysore',25,'India','Hindi','99666666666','Nothing');


